"use client"

import { SparklesIcon } from 'hugeicons-react'
import { Badge } from '@/components/ui/badge'
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip'
import { LLMProvider } from '@/features/conductor/types'
import { cn } from '@/lib/utils'

interface LLMEnhancedBadgeProps {
  isEnhanced: boolean
  provider?: LLMProvider
  isStreaming?: boolean
  modelName?: string
}

export function LLMEnhancedBadge({ isEnhanced, provider, isStreaming, modelName }: LLMEnhancedBadgeProps) {
  if (isStreaming) {
    return (
      <Badge variant="outline" className="gap-1.5 animate-pulse text-primary border-primary/50">
        <SparklesIcon className="h-3 w-3 fill-current" />
        Writing...
      </Badge>
    )
  }

  if (!isEnhanced || !provider) return null

  const providerNames: Record<string, string> = {
    anthropic: "Claude",
    openai: "GPT",
    google: "Gemini",
    xai: "Grok",
  }

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <Badge variant="secondary" className="gap-1.5 text-[10px] h-5 opacity-70 hover:opacity-100 transition-opacity">
            <SparklesIcon className="h-2.5 w-2.5 fill-current" />
            {providerNames[provider] || provider}
          </Badge>
        </TooltipTrigger>
        <TooltipContent>
          <p>This insight was generated by {modelName || providerNames[provider] || provider}</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}
